/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto_TheVoice;

import br.edu.satc.objeto.Candidato;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class CadastroParticipante extends javax.swing.JFrame {

    /**
     * Creates new form CadatroParticipante
     */
    public CadastroParticipante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPpaineldocandidato = new javax.swing.JPanel();
        jLtirulocandidato = new javax.swing.JLabel();
        jLnomeCandidato = new javax.swing.JLabel();
        jTFnomecand = new javax.swing.JTextField();
        jLIdcandidato = new javax.swing.JLabel();
        jTFIdCand = new javax.swing.JTextField();
        jLsexoCandidato = new javax.swing.JLabel();
        jTFsexoCand = new javax.swing.JTextField();
        jLDataNascimento = new javax.swing.JLabel();
        jTFdataNascimentocand = new javax.swing.JTextField();
        jLProfissaodoCandidato = new javax.swing.JLabel();
        jTFprofissaocand = new javax.swing.JTextField();
        jLnascionalidadedoCandidato = new javax.swing.JLabel();
        jTFnascionalidadecand = new javax.swing.JTextField();
        jLTitulo = new javax.swing.JLabel();
        jBCadastroParticipante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPpaineldocandidato.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLtirulocandidato.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLtirulocandidato.setText("Candidato");

        jLnomeCandidato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLnomeCandidato.setText("Nome");

        jLIdcandidato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLIdcandidato.setText("Id");

        jLsexoCandidato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLsexoCandidato.setText("Sexo");

        jLDataNascimento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLDataNascimento.setText("Data de Nascimento");

        jLProfissaodoCandidato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLProfissaodoCandidato.setText("Profissão");

        jLnascionalidadedoCandidato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLnascionalidadedoCandidato.setText("Nascionalidade");

        javax.swing.GroupLayout jPpaineldocandidatoLayout = new javax.swing.GroupLayout(jPpaineldocandidato);
        jPpaineldocandidato.setLayout(jPpaineldocandidatoLayout);
        jPpaineldocandidatoLayout.setHorizontalGroup(
            jPpaineldocandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpaineldocandidatoLayout.createSequentialGroup()
                .addGroup(jPpaineldocandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPpaineldocandidatoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPpaineldocandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFdataNascimentocand)
                            .addComponent(jTFprofissaocand)
                            .addComponent(jTFnascionalidadecand)))
                    .addGroup(jPpaineldocandidatoLayout.createSequentialGroup()
                        .addGroup(jPpaineldocandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPpaineldocandidatoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLnomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPpaineldocandidatoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLIdcandidato))
                            .addGroup(jPpaineldocandidatoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLsexoCandidato))
                            .addGroup(jPpaineldocandidatoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPpaineldocandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLDataNascimento)
                                    .addComponent(jLProfissaodoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLnascionalidadedoCandidato)))
                            .addGroup(jPpaineldocandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTFnomecand, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPpaineldocandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPpaineldocandidatoLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLtirulocandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPpaineldocandidatoLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jTFsexoCand, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPpaineldocandidatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFIdCand, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPpaineldocandidatoLayout.setVerticalGroup(
            jPpaineldocandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpaineldocandidatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLtirulocandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLnomeCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFnomecand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLIdcandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFIdCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLsexoCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFsexoCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLDataNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFdataNascimentocand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLProfissaodoCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFprofissaocand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLnascionalidadedoCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFnascionalidadecand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jLTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLTitulo.setText("Casdatro do Participante");

        jBCadastroParticipante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBCadastroParticipante.setText("Cadastrar");
        jBCadastroParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastroParticipanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBCadastroParticipante)
                            .addComponent(jPpaineldocandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPpaineldocandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCadastroParticipante)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastroParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastroParticipanteActionPerformed
        String NomeParticipante = jTFnomecand.getText();
        int id = 0;
        int idParticipante = Integer.parseInt(jTFIdCand.getText());
        char sexoParticipante = jTFsexoCand.getText().charAt(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date dataNascimentoPartic = sdf.parse(jTFdataNascimentocand.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        String profissaoParticipante = jTFprofissaocand.getText();
        String nascionalidadeParticipante = jTFnascionalidadecand.getText();
        Date dataNascimentoPartic = null;
        
       Candidato c = new Candidato(nascionalidadeParticipante,profissaoParticipante,NomeParticipante,idParticipante,dataNascimentoPartic,sexoParticipante);
        JOptionPane.showMessageDialog(this, c.toString());
        
    }//GEN-LAST:event_jBCadastroParticipanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroParticipante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastroParticipante;
    private javax.swing.JLabel jLDataNascimento;
    private javax.swing.JLabel jLIdcandidato;
    private javax.swing.JLabel jLProfissaodoCandidato;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLnascionalidadedoCandidato;
    private javax.swing.JLabel jLnomeCandidato;
    private javax.swing.JLabel jLsexoCandidato;
    private javax.swing.JLabel jLtirulocandidato;
    private javax.swing.JPanel jPpaineldocandidato;
    private javax.swing.JTextField jTFIdCand;
    private javax.swing.JTextField jTFdataNascimentocand;
    private javax.swing.JTextField jTFnascionalidadecand;
    private javax.swing.JTextField jTFnomecand;
    private javax.swing.JTextField jTFprofissaocand;
    private javax.swing.JTextField jTFsexoCand;
    // End of variables declaration//GEN-END:variables
}
