/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto_TheVoice;

import br.edu.satc.objeto.Apresentacao;
import br.edu.satc.objeto.Candidato;

/**
 *
 * @author SATC
 */
public class CadastroApresentacao extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAvaliacao
     */
    public CadastroApresentacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLautoria = new javax.swing.JLabel();
        jCBsIM = new javax.swing.JCheckBox();
        jCBnao = new javax.swing.JCheckBox();
        jLAdaptacaoApresentacao = new javax.swing.JLabel();
        jCBsimAdaptacao = new javax.swing.JCheckBox();
        jCBnaoAdaptacao = new javax.swing.JCheckBox();
        jLcandidatoApresentacao = new javax.swing.JLabel();
        jTFnomedoCandidato = new javax.swing.JTextField();
        jLMusicaApresentacao = new javax.swing.JLabel();
        jTFmusicaApresentacao = new javax.swing.JTextField();
        jBcadastroDaApresentacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLtitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLtitulo.setText("Cadastro da Apresentação");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLautoria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLautoria.setText("Autoria Própria");

        jCBsIM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCBsIM.setText("Sim");

        jCBnao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCBnao.setText("Não");

        jLAdaptacaoApresentacao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLAdaptacaoApresentacao.setText("Adaptação");

        jCBsimAdaptacao.setText("Sim");

        jCBnaoAdaptacao.setText("Não");

        jLcandidatoApresentacao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLcandidatoApresentacao.setText("Candidato");

        jLMusicaApresentacao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLMusicaApresentacao.setText("Musica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLautoria)
                            .addComponent(jCBsIM)
                            .addComponent(jCBnao))
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBnaoAdaptacao)
                            .addComponent(jCBsimAdaptacao)
                            .addComponent(jLAdaptacaoApresentacao)))
                    .addComponent(jLcandidatoApresentacao)
                    .addComponent(jLMusicaApresentacao)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTFmusicaApresentacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addComponent(jTFnomedoCandidato, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLautoria)
                    .addComponent(jLAdaptacaoApresentacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBsIM)
                    .addComponent(jCBsimAdaptacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBnao)
                    .addComponent(jCBnaoAdaptacao))
                .addGap(18, 18, 18)
                .addComponent(jLcandidatoApresentacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFnomedoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLMusicaApresentacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFmusicaApresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jBcadastroDaApresentacao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBcadastroDaApresentacao.setText("Cadastrar");
        jBcadastroDaApresentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastroDaApresentacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLtitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBcadastroDaApresentacao)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLtitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBcadastroDaApresentacao)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcadastroDaApresentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastroDaApresentacaoActionPerformed
        boolean autoriaApresentacao = Boolean.parseBoolean(jCBsIM.getText()+ jCBnao.getText());
        boolean adaptacao = Boolean.parseBoolean(jCBsimAdaptacao.getText()+ jCBnaoAdaptacao.getText());
        
        
        Apresentacao a = new Apresentacao(autoriaApresentacao,adaptacao,candidatoApresentacao,musicaApresentacao);
        
    }//GEN-LAST:event_jBcadastroDaApresentacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroApresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroApresentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastroDaApresentacao;
    private javax.swing.JCheckBox jCBnao;
    private javax.swing.JCheckBox jCBnaoAdaptacao;
    private javax.swing.JCheckBox jCBsIM;
    private javax.swing.JCheckBox jCBsimAdaptacao;
    private javax.swing.JLabel jLAdaptacaoApresentacao;
    private javax.swing.JLabel jLMusicaApresentacao;
    private javax.swing.JLabel jLautoria;
    private javax.swing.JLabel jLcandidatoApresentacao;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFmusicaApresentacao;
    private javax.swing.JTextField jTFnomedoCandidato;
    // End of variables declaration//GEN-END:variables
}
