/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto_TheVoice;

/**
 *
 * @author SATC
 */
public class CadastroAvaliacao extends javax.swing.JFrame {

    /**
     * Creates new form CadastroApresentacao
     */
    public CadastroAvaliacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtitulo = new javax.swing.JLabel();
        jPpaineldoCadastro = new javax.swing.JPanel();
        jLavaliarApresentacao = new javax.swing.JLabel();
        jTFAvaliarApresent = new javax.swing.JTextField();
        jLrequisito = new javax.swing.JLabel();
        jTFRequisitodaApresentacao = new javax.swing.JTextField();
        jLjurado = new javax.swing.JLabel();
        jTFnomejuradoavaliando = new javax.swing.JTextField();
        jLmediaGeral = new javax.swing.JLabel();
        jTFmediagerAvaliacao = new javax.swing.JTextField();
        jBcadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLtitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLtitulo.setText("Cadastro da Avaliação");

        jPpaineldoCadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLavaliarApresentacao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLavaliarApresentacao.setText("Apresentação");

        jLrequisito.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLrequisito.setText("Requisito");

        jLjurado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLjurado.setText("Jurado");

        jLmediaGeral.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLmediaGeral.setText("Média Geral");

        javax.swing.GroupLayout jPpaineldoCadastroLayout = new javax.swing.GroupLayout(jPpaineldoCadastro);
        jPpaineldoCadastro.setLayout(jPpaineldoCadastroLayout);
        jPpaineldoCadastroLayout.setHorizontalGroup(
            jPpaineldoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpaineldoCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPpaineldoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLavaliarApresentacao)
                    .addComponent(jTFAvaliarApresent)
                    .addComponent(jLrequisito)
                    .addComponent(jTFRequisitodaApresentacao)
                    .addComponent(jLjurado)
                    .addComponent(jTFnomejuradoavaliando)
                    .addComponent(jLmediaGeral)
                    .addComponent(jTFmediagerAvaliacao, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPpaineldoCadastroLayout.setVerticalGroup(
            jPpaineldoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpaineldoCadastroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLavaliarApresentacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFAvaliarApresent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLrequisito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFRequisitodaApresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLjurado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFnomejuradoavaliando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLmediaGeral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFmediagerAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jBcadastro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBcadastro.setText("Cadastrar");
        jBcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBcadastro)
                .addGap(296, 296, 296))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPpaineldoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLtitulo)
                .addGap(18, 18, 18)
                .addComponent(jPpaineldoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBcadastro)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastroActionPerformed
        
    }//GEN-LAST:event_jBcadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAvaliacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastro;
    private javax.swing.JLabel jLavaliarApresentacao;
    private javax.swing.JLabel jLjurado;
    private javax.swing.JLabel jLmediaGeral;
    private javax.swing.JLabel jLrequisito;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPpaineldoCadastro;
    private javax.swing.JTextField jTFAvaliarApresent;
    private javax.swing.JTextField jTFRequisitodaApresentacao;
    private javax.swing.JTextField jTFmediagerAvaliacao;
    private javax.swing.JTextField jTFnomejuradoavaliando;
    // End of variables declaration//GEN-END:variables
}
