/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto_TheVoice;

import br.edu.satc.objeto.Jurado;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class CadastroJurado extends javax.swing.JFrame {

    /**
     * Creates new form CadastroJurado
     */
    public CadastroJurado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jPpaineldoJurado = new javax.swing.JPanel();
        jLnomedojurado = new javax.swing.JLabel();
        jTFNomejurado = new javax.swing.JTextField();
        jLidJurado = new javax.swing.JLabel();
        jTFidDoJurado = new javax.swing.JTextField();
        jLsexoJurado = new javax.swing.JLabel();
        jTFsexoJurado = new javax.swing.JTextField();
        jLdatanascimentojura = new javax.swing.JLabel();
        jTFdataNascimentoJurado = new javax.swing.JTextField();
        jLEspecialidadedoJurado = new javax.swing.JLabel();
        jTFespecialidadedoJurado = new javax.swing.JTextField();
        jBcadastroDoJurado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLTitulo.setText("Cadastro do Jurado");

        jPpaineldoJurado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLnomedojurado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLnomedojurado.setText("Nome");

        jLidJurado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLidJurado.setText("Id");

        jLsexoJurado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLsexoJurado.setText("Sexo");

        jLdatanascimentojura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLdatanascimentojura.setText("Data de Nascimento");

        jLEspecialidadedoJurado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLEspecialidadedoJurado.setText("Especialidade");

        javax.swing.GroupLayout jPpaineldoJuradoLayout = new javax.swing.GroupLayout(jPpaineldoJurado);
        jPpaineldoJurado.setLayout(jPpaineldoJuradoLayout);
        jPpaineldoJuradoLayout.setHorizontalGroup(
            jPpaineldoJuradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpaineldoJuradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPpaineldoJuradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLnomedojurado)
                    .addComponent(jLidJurado)
                    .addComponent(jLsexoJurado)
                    .addComponent(jLdatanascimentojura)
                    .addComponent(jLEspecialidadedoJurado)
                    .addComponent(jTFNomejurado, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(jTFidDoJurado)
                    .addComponent(jTFsexoJurado)
                    .addComponent(jTFdataNascimentoJurado)
                    .addComponent(jTFespecialidadedoJurado))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPpaineldoJuradoLayout.setVerticalGroup(
            jPpaineldoJuradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpaineldoJuradoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLnomedojurado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFNomejurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLidJurado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFidDoJurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLsexoJurado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFsexoJurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLdatanascimentojura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFdataNascimentoJurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLEspecialidadedoJurado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFespecialidadedoJurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jBcadastroDoJurado.setText("Cadastrar");
        jBcadastroDoJurado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastroDoJuradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBcadastroDoJurado)
                            .addComponent(jPpaineldoJurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPpaineldoJurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBcadastroDoJurado)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcadastroDoJuradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastroDoJuradoActionPerformed
        String nomeJurado = jTFNomejurado.getText();
        int idJurado = Integer.parseInt(jTFidDoJurado.getText());
        char sexoJurado = jTFsexoJurado.getText().charAt(0);
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date dataNascimentoJurado = sdf.parse(jTFdataNascimentoJurado.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        String especialidadeJurado = jTFespecialidadedoJurado.getText();
        Date dataNascimentoJurado = null;
        
        Jurado j = new Jurado(especialidadeJurado, nomeJurado,idJurado,dataNascimentoJurado, sexoJurado );
        JOptionPane.showMessageDialog(this, j.toString());
        
        
    }//GEN-LAST:event_jBcadastroDoJuradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroJurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroJurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroJurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroJurado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroJurado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastroDoJurado;
    private javax.swing.JLabel jLEspecialidadedoJurado;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLdatanascimentojura;
    private javax.swing.JLabel jLidJurado;
    private javax.swing.JLabel jLnomedojurado;
    private javax.swing.JLabel jLsexoJurado;
    private javax.swing.JPanel jPpaineldoJurado;
    private javax.swing.JTextField jTFNomejurado;
    private javax.swing.JTextField jTFdataNascimentoJurado;
    private javax.swing.JTextField jTFespecialidadedoJurado;
    private javax.swing.JTextField jTFidDoJurado;
    private javax.swing.JTextField jTFsexoJurado;
    // End of variables declaration//GEN-END:variables
}
