/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto_TheVoice;

import br.edu.satc.objeto.Musica;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class CadastroMusica extends javax.swing.JFrame {

    /**
     * Creates new form CadastroMusica
     */
    public CadastroMusica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLnomeDaMusica = new javax.swing.JLabel();
        jTFnomeMusica = new javax.swing.JTextField();
        jLGenerodaMusica = new javax.swing.JLabel();
        jTFgeneromusica = new javax.swing.JTextField();
        jLartistaDaMusica = new javax.swing.JLabel();
        jTFartistamusica = new javax.swing.JTextField();
        jLtempoMusica = new javax.swing.JLabel();
        jTFtempodamusica = new javax.swing.JTextField();
        jBcadastromusica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro das Musicas");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLnomeDaMusica.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLnomeDaMusica.setText("Nome");

        jTFnomeMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnomeMusicaActionPerformed(evt);
            }
        });

        jLGenerodaMusica.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLGenerodaMusica.setText("Gênero");

        jTFgeneromusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFgeneromusicaActionPerformed(evt);
            }
        });

        jLartistaDaMusica.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLartistaDaMusica.setText("Artista");

        jLtempoMusica.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLtempoMusica.setText("Tempo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLtempoMusica)
                    .addComponent(jLartistaDaMusica)
                    .addComponent(jLGenerodaMusica)
                    .addComponent(jTFnomeMusica)
                    .addComponent(jLnomeDaMusica)
                    .addComponent(jTFgeneromusica, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(jTFartistamusica)
                    .addComponent(jTFtempodamusica))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLnomeDaMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFnomeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLGenerodaMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFgeneromusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLartistaDaMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFartistamusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLtempoMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFtempodamusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jBcadastromusica.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBcadastromusica.setText("Cadastrar");
        jBcadastromusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastromusicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBcadastromusica)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBcadastromusica)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFnomeMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnomeMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnomeMusicaActionPerformed

    private void jTFgeneromusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFgeneromusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFgeneromusicaActionPerformed

    private void jBcadastromusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastromusicaActionPerformed
      String nomeMusica = jTFnomeMusica.getText();
      String generoMusica= jTFgeneromusica.getText();
      int tempoMusica = Integer.parseInt(jTFtempodamusica.getText());
      String ArtistaMusica = jTFartistamusica.getText();
      
      Musica m = new Musica(ArtistaMusica,generoMusica,tempoMusica, ArtistaMusica);
        JOptionPane.showMessageDialog(this, m.toString());
    }//GEN-LAST:event_jBcadastromusicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMusica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastromusica;
    private javax.swing.JLabel jLGenerodaMusica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLartistaDaMusica;
    private javax.swing.JLabel jLnomeDaMusica;
    private javax.swing.JLabel jLtempoMusica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFartistamusica;
    private javax.swing.JTextField jTFgeneromusica;
    private javax.swing.JTextField jTFnomeMusica;
    private javax.swing.JTextField jTFtempodamusica;
    // End of variables declaration//GEN-END:variables
}
